application: memeatnus
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /html
  static_dir: html

- url : /html/css
  static_dir: html/css

- url : /html/js
  static_dir: html/js

- url : /bootstrap/js
  static_dir : bootstrap/js

- url : /bootstrap/css
  static_dir : bootstrap/css

- url: /.*
  script: memeatnus.app

- url : /_ah/upload/.+
  script: memeatnus.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest